+++
date = "2016-01-24T13:28:28+01:00"
title = "Sobre la primera edición"
+++

Han pasado algunos días tras la primera edición de Seville JAM y sólo podemos decir que fue un placer organizar este evento.

Nos gustaría dar las gracias a los participantes y asistentes (algunos vinieron desde Madrid) que supieron crear un ambiente genial. Especial agradecimiento a Emilio por su ayuda en la organización, a Carlos por desplazarse desde Galicia y Pilar (de Espacio RES) por su atención.

Durante este primer encuentro se plantearon dos talleres para futuras ediciones, uno sobre Pipeline y otro sobre testing. Comenzaremos a darle forma en breve.

== Material footnote:[Pendiente de incluir algunos enlaces]

Presentación de Seville JAM:: Presentado por http://manuelrecena.com[Manuel Recena Soto]. https://docs.google.com/presentation/d/1f5Otkz9ymqyXEEuUqzQcTT5UkGHjuIx_j8GelWWYBwo/edit?usp=sharing[Presentación].
Jenkins y kubernetes:: Presentado por http://blog.csanchez.org[Carlos Sánchez].
Pipeline:: Presentado por http://amunizmartin.com[Antonio Manuel Muñiz]
Jenkins y GitHub:: Presentado por http://manuelrecena.com[Manuel Recena Soto]. https://docs.google.com/presentation/d/13nNSBHQA5Ao9Vj4kb8fJJtaKMso2ey7ouZZOLv2CqCI/edit?usp=sharing[Presentación].
Infraestructura de Testing:: Presentado por http://blog.derquinse.net[Andrés Rodríguez].

https://goo.gl/photos/up1s3tZuxV2YTm6W8[Albúm de fotografías].
